# Generated by Django 3.2.8 on 2021-10-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ('homework__course__name', 'homework__name', 'name')},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ('course__name', 'name')},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='text',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
