# Generated by Django 4.0.4 on 2022-05-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_song_gala_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='solfege',
            field=models.TextField(blank=True, null=True),
        ),
    ]
