# Generated by Django 4.0.4 on 2022-06-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_song_solfege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='accesscode',
            unique_together={('course', 'code')},
        ),
    ]
