# Generated by Django 4.1.5 on 2023-01-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_alter_accesscode_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="text",
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
