# Generated by Django 4.1.5 on 2023-03-11 04:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_alter_assignment_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={
                "ordering": ("-homework__course__name", "-homework__name", "-name")
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ("-name",)},
        ),
        migrations.AlterModelOptions(
            name="homework",
            options={"ordering": ("-course__name", "-name")},
        ),
        migrations.AlterField(
            model_name="assignment",
            name="text",
            field=tinymce.models.HTMLField(blank=True, max_length=800, null=True),
        ),
    ]
