# Generated by Django 4.1.5 on 2023-03-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_alter_assignment_options_alter_course_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="upload",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
