# Generated by Django 4.1.5 on 2023-03-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_alter_song_upload"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accesscode",
            options={"ordering": ("-course__name", "code")},
        ),
    ]
