# Generated by Django 4.1.7 on 2023-12-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0013_alter_homework_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="page",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
