# Generated by Django 4.1.7 on 2023-12-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0014_song_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="page",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
